import { Product } from './types'

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 1,
    name: 'Organic Bananas',
    price: 1.50,
    category: 'Fruit',
    image: 'https://images.unsplash.com/photo-1603833665858-e61d17a86224?auto=format&fit=crop&w=400&q=80',
    description: 'Sweet, ripe organic bananas. A great source of potassium and natural energy. Sourced from sustainable farms.',
    inStock: true,
  },
  {
    id: 2,
    name: 'Whole Milk (2L)',
    price: 2.10,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1550583724-1255818c053b?auto=format&fit=crop&w=400&q=80',
    description: 'Fresh whole milk from grass-fed cows. Rich in calcium and vitamins. Delivered fresh daily.',
    inStock: true,
  },
  {
    id: 3,
    name: 'Sourdough Bread',
    price: 3.20,
    category: 'Bakery',
    image: 'https://images.unsplash.com/photo-1585478259715-876acc5be8eb?auto=format&fit=crop&w=400&q=80',
    description: 'Crusty, artisanal sourdough baked fresh every morning. Slow-fermented for 24 hours for the best flavour.',
    inStock: true,
  },
  {
    id: 4,
    name: 'Avocados (2pk)',
    price: 2.50,
    category: 'Fruit',
    image: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?auto=format&fit=crop&w=400&q=80',
    description: 'Creamy, ripe avocados perfect for salads or toast. Locally sourced and organic. Grown without synthetic pesticides.',
    inStock: true,
    badge: 'Bestseller',
  },
  {
    id: 5,
    name: 'Vine Tomatoes',
    price: 1.80,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=400&q=80',
    description: 'Juicy vine-ripened tomatoes bursting with flavour. Perfect for salads, sauces, or roasting.',
    inStock: true,
  },
  {
    id: 6,
    name: 'Greek Yogurt',
    price: 1.95,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?auto=format&fit=crop&w=400&q=80',
    description: 'Thick, creamy Greek yogurt. High in protein and probiotics. Great for breakfast or cooking.',
    inStock: true,
  },
  {
    id: 7,
    name: 'Spinach (200g)',
    price: 1.20,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?auto=format&fit=crop&w=400&q=80',
    description: 'Fresh baby spinach leaves, pre-washed and ready to eat. Packed with iron and vitamins.',
    inStock: true,
  },
  {
    id: 8,
    name: 'Pink Lady Apples',
    price: 2.00,
    category: 'Fruit',
    image: 'https://images.unsplash.com/photo-1560806887-1e480c8ca0ff?auto=format&fit=crop&w=400&q=80',
    description: 'Crisp, sweet-tart Pink Lady apples. Perfect for snacking or baking. Sustainably grown in Kent.',
    inStock: true,
  },
  {
    id: 9,
    name: 'Fresh Strawberries',
    price: 2.80,
    category: 'Fruit',
    image: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?auto=format&fit=crop&w=400&q=80',
    description: 'Sweet, juicy British strawberries picked at peak ripeness. Ideal for desserts or eating fresh.',
    inStock: true,
  },
  {
    id: 10,
    name: 'Free Range Eggs',
    price: 2.40,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1506976785307-8732e854ad03?auto=format&fit=crop&w=400&q=80',
    description: 'A dozen large free-range eggs from happy hens. Rich golden yolks and full flavour.',
    inStock: true,
  },
  {
    id: 11,
    name: 'Red Bell Pepper',
    price: 0.80,
    category: 'Vegetables',
    image: 'https://images.unsplash.com/photo-1563513130-18458788448d?auto=format&fit=crop&w=400&q=80',
    description: 'Sweet, crunchy red peppers. Great for stir-fries, roasting, or eating raw. High in vitamin C.',
    inStock: true,
  },
  {
    id: 12,
    name: 'Unsalted Butter',
    price: 1.75,
    category: 'Dairy',
    image: 'https://images.unsplash.com/photo-1589985270826-4b7bb135bc9d?auto=format&fit=crop&w=400&q=80',
    description: 'Churned from the finest cream. Ideal for baking, cooking, and spreading. No added salt.',
    inStock: true,
  },
]

export const RELATED_PRODUCTS: Product[] = [
  {
    id: 13,
    name: 'Vine Tomatoes',
    price: 1.50,
    category: 'Vegetables',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuB0nMt010-ICYoS9cRv-lVwXDFJkZlpiT9FFGP_YgAWqbaJjlk7qv3a_4VwT55W7YRZ6IMS7BfM3NI7vcmZJsq9fetbB6vxPUqTcBujK5woM9wIDySIPri5bFe4ttWf41ZBUVXEqSbIUgXUaQh8QFMmKchUDxgmJaDDscVo1-xtWG54B_HJJSXZ79FIoZhSVaMow7dLr-mECRHWQox8DwZww98oWTorc905f48RS_tSaAGOLEMiT7fbOZi1NEAgLwxImVPvCy7U-qRJ',
  },
  {
    id: 14,
    name: 'Fresh Limes (3pk)',
    price: 0.95,
    category: 'Fruit',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCa1SPtGFX9rhZU-5L9vWaZIw0iG_AUQdxDb5C4QKePUXk848ByRoEGYlNpyAwcCveo4NnnMFXyPSa2VE5OmpzzpjaPqllajOnjcPMoLsfAKCo168cBf0d8l04MnBbD4kAAwe11zS9HNvXUCE-TgWkGeL_etjMhzZ25PxiufJJiUq_r4qPQRmwpzSSo9ELfrxrfBdPZURDUb0A3KpDbGs0VDBuW1vuhaH4xILM7Cx7BUz05Z043USUwC1w-t2pOjTgEjn7JYKbYe9Ck',
  },
  {
    id: 15,
    name: 'Artisan Sourdough',
    price: 3.20,
    category: 'Bakery',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDMGcQ73PxBIVFeLboN3N1n0DJ53JqcElnw3nDb8UKPGUFcUveIkjKxb5MjP1H0_jJxlRvieWLjdDyXf9mUiFMbe_2YFZ1hkHkYVxFbgxmkDc2Nr7hGy0ewcMwkoLUZK9ZR-3SXxS6IZ_Qgx-POMjsO03y3tN0t_wAjrL8fl6jHvzFcK1JCi0K7ViZPH__D4pUt7Z45cwTu5r3W46DSIvgQ0MZES8Ug1r9Zlg9RSEej7qSjEIKMAz7EeA-dLD0vNLpmr2IDoIzsr2QO',
  },
  {
    id: 16,
    name: 'Organic Lemons',
    price: 1.20,
    category: 'Fruit',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuDO2Wy4NHsEh6BMsBqcX8XcKavfLWBuCG9VDOzOXExLSyPb2dJjE-yfjs45ly7ivQ8d4x7VqrXJwMOomF4-lQMV3vrCY2K85f0jeKP5hKmMod9Xt2pN7DPNb_NjGw-m7mxQOYevZK1mp03lZ0gHdpTKo2xVQmd3JLhijs5PwmMGoENjTr9dSZykYC4oC_EV_T0m-GmNM6weHQdTou_8x92PC-SLd15MZI9PEBuQwNW9ZkbsYrxOlbZHaPxLwpNpnkC7jP2TTHSXSW6j',
  },
]
