import type { Config } from 'tailwindcss'

const config: Config = {
  darkMode: 'class',
  content: [
    './app/**/*.{ts,tsx}',
    './components/**/*.{ts,tsx}',
    './context/**/*.{ts,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'surface-container-lowest': '#ffffff',
        'surface-container-low':    '#f6f3f2',
        'surface-container':        '#f0eded',
        'surface-container-high':   '#eae7e7',
        'surface-container-highest':'#e5e2e1',
        'surface':                  '#fcf9f8',
        'surface-dim':              '#dcd9d9',
        'surface-bright':           '#fcf9f8',
        'surface-variant':          '#e5e2e1',
        'surface-tint':             '#2a6b2c',
        'on-surface':               '#1c1b1b',
        'on-surface-variant':       '#41493e',
        'inverse-surface':          '#313030',
        'inverse-on-surface':       '#f3f0ef',
        'outline':                  '#717a6d',
        'outline-variant':          '#c0c9bb',
        'primary':                  '#00450d',
        'on-primary':               '#ffffff',
        'primary-container':        '#1b5e20',
        'on-primary-container':     '#90d689',
        'primary-fixed':            '#acf4a4',
        'primary-fixed-dim':        '#91d78a',
        'on-primary-fixed':         '#002203',
        'on-primary-fixed-variant': '#0c5216',
        'inverse-primary':          '#91d78a',
        'secondary':                '#9e4200',
        'on-secondary':             '#ffffff',
        'secondary-container':      '#fb6d00',
        'on-secondary-container':   '#562100',
        'secondary-fixed':          '#ffdbcb',
        'secondary-fixed-dim':      '#ffb691',
        'on-secondary-fixed':       '#341100',
        'on-secondary-fixed-variant':'#793100',
        'tertiary':                 '#323e36',
        'on-tertiary':              '#ffffff',
        'tertiary-container':       '#49554c',
        'on-tertiary-container':    '#bcc9be',
        'tertiary-fixed':           '#d9e6da',
        'tertiary-fixed-dim':       '#bdcabe',
        'on-tertiary-fixed':        '#131e17',
        'on-tertiary-fixed-variant':'#3e4a41',
        'error':                    '#ba1a1a',
        'on-error':                 '#ffffff',
        'error-container':          '#ffdad6',
        'on-error-container':       '#93000a',
        'background':               '#fcf9f8',
        'on-background':            '#1c1b1b',
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        base:             '4px',
        xs:               '4px',
        sm:               '8px',
        md:               '16px',
        lg:               '24px',
        xl:               '32px',
        xxl:              '48px',
        gutter:           '24px',
        'container-max':  '1280px',
        'margin-desktop': '32px',
        'margin-mobile':  '16px',
      },
      fontSize: {
        'display-lg':        ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg':       ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile':['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-md':       ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-sm':       ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg':           ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md':           ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-sm':           ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'label-lg':          ['14px', { lineHeight: '20px', letterSpacing: '0.01em', fontWeight: '600' }],
        'label-sm':          ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
      maxWidth: {
        'container-max': '1280px',
      },
    },
  },
  plugins: [],
}

export default config
